Milestone 4: Category filter
macbright/bookstore pull request #4
Opened 2020-01-13 13:52 UTC by shshamim63

## :white_check_mark: The Pull Request contains the following task:
---

1. Enhances redux store with a filter field.
   ...1. contains current filtered data.
   ...2. Handles All and initial state not selected factor.
2. Contains CategoryFilter component.
   ...1. Components render a selectbox with all the categories.
   ...2. Merges the initial selection All type.
3. Updates filter value on the redux store.
   ...1. Render books that are matched with the current filter value.
   ...2. Implemented a conditional method which should handle to filter the books based on category.

2020-01-13 16:06 UTC, jofer86 requested changes
## 👋 👋 Hello Team. Just dropping by to review this milestone, let's take a closer look at your code shall we 👁 👁 👁 

- There is a couple of changes that need to be implemented before you can move on to the next project, those changes are outlined below. Please make sure you tend to those and then request for another code review. Changes are minor, but you should adjust your code accordingly if your changes affect other parts of your app.

--------------------------------------------------------------------
Cheers,
Jorge Fernando Rincón Figueroa.
Technical Support Engineer.
**Slack: @jofer86**

2020-01-13 16:06 UTC, jofer86 commented on src/reducers/filter.js
> +const bookFilter = (state = '', action) => {
We need to make sure to default this to `'All'` as stated in the [Pathwright to this project](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896829/)
![image](https://user-images.githubusercontent.com/46115725/72269364-14276680-35e9-11ea-92cb-c3311372da97.png)

2020-01-13 16:06 UTC, jofer86 commented on src/utils/filterbooks.js
> +  if (filter !== '' && filter !== 'All') {
Like it was said on the comment posted in the filter.js file if we default to  `'All'` there would not be necessary for you to pass `''` as a category to filter the books, leaving the filtering defaulted to all should take care of it.

2020-01-13 16:08 UTC, jofer86 commented on src/containers/BookList.js
>                title={book.title}
- We need to make sure that the books are rendered with a conditional statement as stated in [in the Pathwirght to this project](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/44896829/)
![image](https://user-images.githubusercontent.com/46115725/72271530-abda8400-35ec-11ea-9bcf-5d8ef1e42da7.png)

2020-01-14 04:21 UTC, bellom approved these changes
## Hi Team :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Goodluck in the next project :slightly_smiling_face:_ 

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-01-14 08:08 UTC, merged